### ISSUE TITLE
research AragonOs

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-contracts#227]
Question: could we implement our company governance using AragonOS? We need a short overview on how it works and what governance modules are available. There are core concepts like aragon organizations, tokens, permissions etc.

Specifically regarding the code
1. modularity - can new functional modules be added? like whitelist to token controller onTransfer. how modularity is done in AragonOs?
2. execution of custom code snippets for example as a result of voting? they have some evm snippets but how can be those used?
3. upgradibility of contracts: is it forwarding proxy? or maybe modules are libraries and there's some structured storage?
4. permission system: how you can define who can do which action in the organization?
5. OPTIONAL: is our snapshot token compatible with MiniMe in AragonOs? If no one is relying on snapshotId being block number then yes

**Comment by djudjuu** [comment]
notes: most relevant links for now:

https://hack.aragon.org/docs/aragonos-intro

https://hack.aragon.org/docs/aragonos-building#forwarding-and-evmscripts
