### ISSUE TITLE
add new fixtures to test migrations and document it

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-contracts#237]
Here's list of fixtures
```
Wallet 1 similar to INV_EUR_ICBM_HAS_KYC_SEED
Wallet 2 similar to INV_ETH_ICBM_NO_KYC
Wallet 3 similar to INV_ICBM_ETH_M_HAS_KYC_DUP
Wallet 4 similar to INV_ICBM_ETH_M_HAS_KYC_DUP but with Neuro Claimed 
Wallet 5 similar to INV_EUR_ICBM_HAS_KYC_SEED
Wallet 6 similar to INV_ETH_EUR_ICBM_M_HAS_KYC_DUP but with some nEur and without Eth (ICMB eth and ICBM neur should still be there)
```

they all are actively doing transactions so you will need to add them to parity self seal node and unlock them. sometimes test need derivation path, please align with @banciur how to add those to parity

then update documentation

**Comment by drakkein** [comment]
Besides fixture we talked about on slack, which is one with small amount of ETH or nEUR in incoming and ready to claim payouts, please update `INV_ETH_EUR_ICBM_HAS_KYC` and `INV_ETH_EUR_ICBM_M_HAS_KYC_DUP` to have more than 1 ETH in both incoming and claimable payouts.
