### ISSUE TITLE
add nominee per eto fixture

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-contracts#290]
**Background**
We are implementing full Nominee flow and the default is that each eto has separate Nominee. Make it happen in our fixtures!

**Acceptance Criteria**
* [x] i can configure nominee per ETO as I configure the ISSUER
* [x] it should be possible to assign nominee to many ETOs - that's what we have right now
* [x] modify ETO deployment so right nominee (the one configured is used and that it signs THA)
* [x] and add those nominee fixtures. each ETO has a separate nominee.
* [x] make one exception for current nominee - keep it in NO_START_DATE issuer and SETUP_ISSUER to test multi ETO case.

**Comment by Exef** [comment]
TODO:
- [ ] Walkthrough current state of the ETO fixture creation and deployment
- [ ] Add `10X_migration` that will assign nominee to the ETO
- [ ] Add property to the `fixtures_definition.json` with a list of ETOs linked to the nominee
- [ ] Modify `yarn fixture:add` to ask different questions during nominee fixture creation.


THA - Token Holder Agreement
