### ISSUE TITLE
implement mock that accepts ETH and accepts/rejects ERC223 transfers

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-contracts#320]
**Why we do it**
Due to Istanbul fork we cannot use `SimpleExchange` to test ETH transfer contract to contract. (we had event there that now crosses 2300 gas stipend of fallback function)
We need to reintroduce those e2e tests

**What we do**
We need a contract that will be deployed on dev (loclahost) env against which we can test ETH transfer. On top of that let's add ERC223 callback for testing ERC223 transfer for which we do not have coverage at all

**Acceptance criteria**
* [ ] implements payable callback function
* [ ] function above can be called via another contract (test!)
* [ ] implements IERC223Callback
* [ ] implements IERC223LegacyCallback (to test NEU which requires old callback ;/)
* [ ] provides a mock method to accepts/reject erc223 transfers transfers in the callback function

**Deployment**
* [ ] make it a part of deployment pipeline so it gets deployed only on dev.

**Comment by Moejoe90** [comment]
Basically the conract should also Accept 
Ether
Plus work with `TransferAndSend` method provided by ethertoken
