### ISSUE TITLE
voting center contract

### ISSUE THREAD

**Issue by djudjuu** [Neufund/platform-contracts#331]
### WHAT
we want new voting based  on equity-tokens that upon a threshold notifies all token-holders that they need to vote too: Therefore we want 3 contracts: 

##### Vote parameters:
  - [x] a unique resolution_id
  - [ ] a name (string)
  - [ ] an ipfs hash holding a document what is to be voted on (maybe the resolutionId can serve as all of that? do we really need an extra string?)
  - [x] duration, total amount of time during which tokenholders can vote
  - [x] votes are final
  - [x] campaign-quorum, which when reached should fire an event to notify all tokenholders
  - [x] campaign deadling, until which campaign quorum must be reached
  - [ ] data to encode the onchain-consequences of the vote: 
      - Maybe: address & action_id (hash of the function signature of the method to be called) 
      - parameters (encoded as bytes) in function to be called (should be added with #332)  
 - [x] Snapshottable Token on which voting is based
 - [ ] offchainVoteParamters: 
      1) percentage of total Votes coming from outside, 
      2) address which is allowed to put them in, 
      3) duration after end of public-phase during which offchain votes can still be submitted

 
#### Mechanics
The Voting Center should
- [ ] be registered as a singleton with the universe contract
- [ ] verify some basic assumptions about the different durations, such that the total period is longer than campaign and count up votes and leave the res to the VotingController (see #334 )
- [ ] provides way for offchain-votes to be entered, before, but also after end of public voting-period
- [ ] only tracks vote count and provides ```getVoteFinalCount(inFavor, Against, Total)```, where total is the total amount of possible votes
- [ ] logs events if the there was a successful campaign phase
- [ ] logs an event to indicate that a vote is final (no more votes can be added)

possibly extensions to keep in mind, would be how to do quadratic voting, (could just be another contract, but maybe we can do some nice inheritance here)

### State-diagram

![IMG_20200312_172132945](https://user-images.githubusercontent.com/9882716/76543363-b4352b00-6486-11ea-879a-71bda3337cb1.jpg)

**Comment by rudolfix** [comment]
1. we want our voting to work for any snapshottable token issued on the platform, not just equity-tokens...
2. let's work on two first contract first (Voting-Center) and Voting Controller
3. some high level assumptions are missing
- voting center is a platform singleton and available via Universe
- it handles many concurrent votes on many differnt tokens
- votes are identified by resolution id (bytes32)
- yes/no votes only
- voting is final (?) per voting address
4. you could provide a simple state diagram of the voting process
5. providing offchain votes requires establishing legal representative of the voting process (it's just address) - and is of course optional
6. Let's specify VotingController in more detail. What it is going to control?
- which tokens may be used for voting and who can initialize voting for particular vote

7. What about defining some interface that voting initializer implement and that will return voting result by resolution id
like
votingResult(resolutionId) returns (VotingResult: voting pending|yes|no|)

**Comment by djudjuu** [comment]
> at voting initializer implement and that will return voting result by resolution id

i dont understand what you mean by voting-initializer?  where should that be implemented? the example you gave sounds more like it would be placed in the Voting-contract so that the VoteControlled-Mixin could query it.
